import Link from 'next/link';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav>
          <div>
            <Link data-test-id="home" href="/">
              home
            </Link>{' '}
            <Link data-test-id="cookie" href="/cookie">
              set-cookie
            </Link>{' '}
            <Link data-test-id="test" href="/test">
              test-cookie
            </Link>{' '}
            <Link data-test-id="page" href="/page">
              page
            </Link>{' '}
            <Link data-test-id="timeout" href="/timeout">
              timeout
            </Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
